### ISSUE TITLE
Does NOT work

### ISSUE THREAD

**Issue by vitusq** [brenkster/Get-ExchangeCUandSUcopytoServers#1]
It isn't able to download new CU updates. It can only identify & download an older version. 

Then again, those fail as well.. So pretty much a useless script.

**Comment by vitusq** [comment]
Also, this is outdated now and does not have added the ability to download the latest SU for all Exchange versions. 

Please update

**Comment by brenkster** [comment]
Did you read and use this:
Run the module as follows:

Import-Module yourpath\Get-ExchangeCUandSUcopytoServers.psm1

Get-ExchangeCU -Version 2019_CU11_SU_JAN_2022 -Directory C$\Temp -Name server1,server2 -RemoveTemp

**Comment by brenkster** [comment]
Latest CU's were added 21-04-2022
